site_name: FHIRcast

nav:
    - Home: index.md
    - Specification: 
        - 'Current - STU2': 'specification/STU2.md'
        - 'STU1': 'specification/STU1.md'
    - Event Catalog: 
        - new-event-template: events/template.md
        - syncerror: events/syncerror.md
        - userlogout: events/userlogout.md
        - userhibernate: events/userhibernate.md
        - Patient-open: events/patient-open.md
        - Patient-close: events/patient-close.md
        - ImagingStudy-open: events/imagingstudy-open.md
        - ImagingStudy-close: events/imagingstudy-close.md
    - Launch Scenarios: launch-scenarios.md
    - Synchronization Considerations: syncconsiderations.md
    - Security Considerations: security-considerations.md
    - Multi-tab Considerations: multitab-considerations.md
    - About: about.md
theme: readthedocs

markdown_extensions:
  - admonition

copyright: ®© HL7.org 2017+ <a rel="license" href="https://www.hl7.org/fhir/license.html"><img src="https://www.hl7.org/fhir/cc0.png" alt="CC0"></a>
