site_name: FHIRcast
pages:
    - Home: index.md
    - Specification: 
        - 'May2019Ballot': 'specification/May2019Ballot.md'
    - Launch Scenarios: launch-scenarios.md
    - Synchronization Considerations: syncconsiderations.md
    - Security Considerations: security-considerations.md
    - About: about.md
theme: readthedocs

copyright: ®© HL7.org 2017+ <a rel="license" href="https://www.hl7.org/fhir/license.html"><img src="https://www.hl7.org/fhir/cc0.png" alt="CC0"></a>